### ISSUE TITLE
After update to 1.2.* need to refresh tests in order to get latest test output

### ISSUE THREAD

**Issue by sashberd** [vitest-dev/vscode#472]
### Describe the bug

After updating to version 1.2.*, the extension seems to be caching outdated code, leading to incorrect test results. To obtain accurate test output, it is necessary to refresh the tests.

### Reproduction

![20240918_095813](https://github.com/user-attachments/assets/1692a28d-86de-4112-93c1-9d9947bdf220)

### Output

```shell
As shown in the attached video, you may need to press Ctrl+;+R to refresh your code and ensure that the latest changes are reflected in the test results."

The Output:
[INFO 10:03:13 AM] Running 1 file(s) with name pattern: ^\s?CorrectDiagnosticArea component unit tests
[10:03:13 AM] The runner is starting because tests C:/Users/LQ4161/Desktop/Dev/darwin-web/src/tests/app/modules/report-status/correctDiagnosticArea.test.tsx were started due to a file change
[10:03:13 AM] Enqueuing "CorrectDiagnosticArea component unit tests
[10:03:13 AM] Enqueuing "should render component in case of state is pending close
[10:03:17 AM] No task result for "should render component in case of state is pending close", assuming the test just started running
[10:03:17 AM] Marking "should render component in case of state is pending close" as passed
[10:03:17 AM] Ending test run src/tests/app/modules/report-status/correctDiagnosticArea.test.tsx
[INFO 10:03:21 AM] Running 1 file(s) with name pattern: ^\s?CorrectDiagnosticArea component unit tests
[10:03:21 AM] The runner is starting because tests C:/Users/LQ4161/Desktop/Dev/darwin-web/src/tests/app/modules/report-status/correctDiagnosticArea.test.tsx were started due to a file change
[10:03:21 AM] Enqueuing "CorrectDiagnosticArea component unit tests
[10:03:21 AM] Enqueuing "should render component in case of state is pending close
[10:03:25 AM] No task result for "should render component in case of state is pending close", assuming the test just started running
[10:03:25 AM] Marking "should render component in case of state is pending close" as passed
[10:03:25 AM] Ending test run src/tests/app/modules/report-status/correctDiagnosticArea.test.tsx
[INFO 10:03:27 AM] [API] Vitest process 23148 closed successfully
[INFO 10:03:27 AM] [API] Running Vitest v2.0.5 (darwin-web/vitest.config.ts) with Node.js: C:\Program Files\nodejs\node.EXE
[INFO 10:03:28 AM] [API] Vitest v2.0.5 (darwin-web/vitest.config.ts) process 17372 created
[INFO 10:03:28 AM] [API] Collecting tests: src/tests/app/modules/report-status/correctDiagnosticArea.test.tsx
[10:03:28 AM] Not starting the runner because tests are being collected
[10:03:33 AM] There is no test run for "correctDiagnosticArea.test.tsx"
[10:03:33 AM] No test run to finish for C:/Users/LQ4161/Desktop/Dev/darwin-web/src/tests/app/modules/report-status/correctDiagnosticArea.test.tsx
[INFO 10:03:34 AM] Running 1 file(s) with name pattern: ^\s?CorrectDiagnosticArea component unit tests
[10:03:34 AM] The runner is starting because tests C:/Users/LQ4161/Desktop/Dev/darwin-web/src/tests/app/modules/report-status/correctDiagnosticArea.test.tsx were started due to a file change
[10:03:34 AM] Enqueuing "CorrectDiagnosticArea component unit tests
[10:03:34 AM] Enqueuing "should render component in case of state is pending close
[10:03:39 AM] No task result for "should render component in case of state is pending close", assuming the test just started running
[10:03:39 AM] No errors found for "correctDiagnosticArea.test.tsx"
[10:03:39 AM] No errors found for "CorrectDiagnosticArea component unit tests"
[10:03:39 AM] Could not find a valid stack for should render component in case of state is pending close [
  {
    "method": "assertNotNullOrUndefined",
    "file": "C:/Users/LQ4161/Desktop/Dev/darwin-web/node_modules/.pnpm/@testing-library+dom@9.3.4/node_modules/@testing-library/dom/dist/matches.js",
    "line": 12,
    "column": 11
  },
  {
    "method": "matches",
    "file": "C:/Users/LQ4161/Desktop/Dev/darwin-web/node_modules/.pnpm/@testing-library+dom@9.3.4/node_modules/@testing-library/dom/dist/matches.js",
    "line": 35,
    "column": 3
  },
  {
    "method": "",
    "file": "C:/Users/LQ4161/Desktop/Dev/darwin-web/node_modules/.pnpm/@testing-library+dom@9.3.4/node_modules/@testing-library/dom/dist/query-helpers.js",
    "line": 37,
    "column": 82
  },
  {
    "method": "queryAllByAttribute",
    "file": "C:/Users/LQ4161/Desktop/Dev/darwin-web/node_modules/.pnpm/@testing-library+dom@9.3.4/node_modules/@testing-library/dom/dist/query-helpers.js",
    "line": 37,
    "column": 67
  },
  {
    "method": "queryAllByTestId",
    "file": "C:/Users/LQ4161/Desktop/Dev/darwin-web/node_modules/.pnpm/@testing-library+dom@9.3.4/node_modules/@testing-library/dom/dist/queries/test-id.js",
    "line": 13,
    "column": 44
  },
  {
    "method": "",
    "file": "C:/Users/LQ4161/Desktop/Dev/darwin-web/node_modules/.pnpm/@testing-library+dom@9.3.4/node_modules/@testing-library/dom/dist/query-helpers.js",
    "line": 74,
    "column": 17
  },
  {
    "method": "",
    "file": "C:/Users/LQ4161/Desktop/Dev/darwin-web/node_modules/.pnpm/@testing-library+dom@9.3.4/node_modules/@testing-library/dom/dist/query-helpers.js",
    "line": 52,
    "column": 17
  },
  {
    "method": "",
    "file": "C:/Users/LQ4161/Desktop/Dev/darwin-web/node_modules/.pnpm/@testing-library+dom@9.3.4/node_modules/@testing-library/dom/dist/query-helpers.js",
    "line": 95,
    "column": 19
  },
  {
    "method": "",
    "file": "C:/Users/LQ4161/Desktop/Dev/darwin-web/src/tests/app/modules/report-status/correctDiagnosticArea.test.tsx",
    "line": 33,
    "column": 19
  }
]
[10:03:39 AM] Marking "should render component in case of state is pending close" as failed with 1 errors
[10:03:39 AM] No errors found for "correctDiagnosticArea.test.tsx"
[10:03:39 AM] Ending test run src/tests/app/modules/report-status/correctDiagnosticArea.test.tsx
[INFO 10:03:45 AM] Running 1 file(s) with name pattern: ^\s?CorrectDiagnosticArea component unit tests
[10:03:45 AM] The runner is starting because tests C:/Users/LQ4161/Desktop/Dev/darwin-web/src/tests/app/modules/report-status/correctDiagnosticArea.test.tsx were started due to a file change
[10:03:45 AM] Enqueuing "CorrectDiagnosticArea component unit tests
[10:03:45 AM] Enqueuing "should render component in case of state is pending close
[10:03:49 AM] No task result for "should render component in case of state is pending close", assuming the test just started running
[10:03:49 AM] No errors found for "correctDiagnosticArea.test.tsx"
[10:03:49 AM] No errors found for "CorrectDiagnosticArea component unit tests"
[10:03:49 AM] Could not find a valid stack for should render component in case of state is pending close [
  {
    "method": "assertNotNullOrUndefined",
    "file": "C:/Users/LQ4161/Desktop/Dev/darwin-web/node_modules/.pnpm/@testing-library+dom@9.3.4/node_modules/@testing-library/dom/dist/matches.js",
    "line": 12,
    "column": 11
  },
  {
    "method": "matches",
    "file": "C:/Users/LQ4161/Desktop/Dev/darwin-web/node_modules/.pnpm/@testing-library+dom@9.3.4/node_modules/@testing-library/dom/dist/matches.js",
    "line": 35,
    "column": 3
  },
  {
    "method": "",
    "file": "C:/Users/LQ4161/Desktop/Dev/darwin-web/node_modules/.pnpm/@testing-library+dom@9.3.4/node_modules/@testing-library/dom/dist/query-helpers.js",
    "line": 37,
    "column": 82
  },
  {
    "method": "queryAllByAttribute",
    "file": "C:/Users/LQ4161/Desktop/Dev/darwin-web/node_modules/.pnpm/@testing-library+dom@9.3.4/node_modules/@testing-library/dom/dist/query-helpers.js",
    "line": 37,
    "column": 67
  },
  {
    "method": "queryAllByTestId",
    "file": "C:/Users/LQ4161/Desktop/Dev/darwin-web/node_modules/.pnpm/@testing-library+dom@9.3.4/node_modules/@testing-library/dom/dist/queries/test-id.js",
    "line": 13,
    "column": 44
  },
  {
    "method": "",
    "file": "C:/Users/LQ4161/Desktop/Dev/darwin-web/node_modules/.pnpm/@testing-library+dom@9.3.4/node_modules/@testing-library/dom/dist/query-helpers.js",
    "line": 74,
    "column": 17
  },
  {
    "method": "",
    "file": "C:/Users/LQ4161/Desktop/Dev/darwin-web/node_modules/.pnpm/@testing-library+dom@9.3.4/node_modules/@testing-library/dom/dist/query-helpers.js",
    "line": 52,
    "column": 17
  },
  {
    "method": "",
    "file": "C:/Users/LQ4161/Desktop/Dev/darwin-web/node_modules/.pnpm/@testing-library+dom@9.3.4/node_modules/@testing-library/dom/dist/query-helpers.js",
    "line": 95,
    "column": 19
  },
  {
    "method": "",
    "file": "C:/Users/LQ4161/Desktop/Dev/darwin-web/src/tests/app/modules/report-status/correctDiagnosticArea.test.tsx",
    "line": 33,
    "column": 19
  }
]
[10:03:49 AM] Marking "should render component in case of state is pending close" as failed with 1 errors
[10:03:49 AM] No errors found for "correctDiagnosticArea.test.tsx"
[10:03:49 AM] Ending test run src/tests/app/modules/report-status/correctDiagnosticArea.test.tsx
[INFO 10:03:52 AM] [API] Vitest process 17372 closed successfully
[INFO 10:03:52 AM] [API] Running Vitest v2.0.5 (darwin-web/vitest.config.ts) with Node.js: C:\Program Files\nodejs\node.EXE
[INFO 10:03:52 AM] [API] Vitest v2.0.5 (darwin-web/vitest.config.ts) process 20768 created
[INFO 10:03:52 AM] [API] Collecting tests: src/tests/app/modules/report-status/correctDiagnosticArea.test.tsx
[10:03:52 AM] Not starting the runner because tests are being collected
[10:03:58 AM] There is no test run for "correctDiagnosticArea.test.tsx"
[10:03:58 AM] No test run to finish for C:/Users/LQ4161/Desktop/Dev/darwin-web/src/tests/app/modules/report-status/correctDiagnosticArea.test.tsx
[INFO 10:03:59 AM] Running 1 file(s) with name pattern: ^\s?CorrectDiagnosticArea component unit tests
[10:03:59 AM] The runner is starting because tests C:/Users/LQ4161/Desktop/Dev/darwin-web/src/tests/app/modules/report-status/correctDiagnosticArea.test.tsx were started due to a file change
[10:03:59 AM] Enqueuing "CorrectDiagnosticArea component unit tests
[10:03:59 AM] Enqueuing "should render component in case of state is pending close
[10:04:04 AM] No task result for "should render component in case of state is pending close", assuming the test just started running
[10:04:04 AM] Marking "should render component in case of state is pending close" as passed
[10:04:04 AM] Ending test run src/tests/app/modules/report-status/correctDiagnosticArea.test.tsx
```

### Version

1.2.7

VSCode Data:
Version: 1.93.0 (user setup)
Commit: 4849ca9bdf9666755eb463db297b69e5385090e3
Date: 2024-09-04T13:02:38.431Z
Electron: 30.4.0
ElectronBuildId: 10073054
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.19045

### Validations

- [X] Check that you are using the latest version of the extension
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vscode/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vscode/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AriPerkkio** [comment]
Are you sure this is caused by the extension? There's an open issue on VSCode too: https://github.com/microsoft/vscode/issues/222098#issuecomment-2354707505.

I'm seeing this same bug even when I disable the extension completely.

**Comment by sashberd** [comment]
@AriPerkkio You are right! After I disabled _`TypeScript › Tsserver › Experimental: Use Vs Code Watcher`_, it works without refresh. 
However, now it looks like it stuck after changes and won`t run again. Only debug option runs the tests
(It started run again after at least 15 seconds of wait)


![20240918_112317](https://github.com/user-attachments/assets/c88b4807-6ff6-4ace-b5e5-26cd89d20ce9)

**Comment by Igor-Vuk** [comment]
Yes. Me to. After a change, tests are not run again. Only way is to use debug mode to trigger them again.

**Comment by Igor-Vuk** [comment]
Ahh, it was short lived. It stopped watching tests again even if TypeScript>Tsserver>Experimental is turned off.

**Comment by sheremet-va** [comment]
Does the issue happen if you edit the test file or if you edit its dependency?

**Comment by sheremet-va** [comment]
This should be fixed in 1.2.9

**Comment by Igor-Vuk** [comment]
> Does the issue happen if you edit the test file or if you edit its dependency?

when I'm editing test files. If I run vitest in bash, it reloads tests on every file change. The vitest extension doesn't. I need to run Refresh tests and than Run Tests to get the new data. If I go to "vitest.config.ts", make a change, and save, then the extension reruns the tests, but in any other file it doesn't.

**Comment by olafure** [comment]
This is still a problem in 1.2.11.

**Comment by jimmyn** [comment]
I have the same issue with v1.2.12

**Comment by LaurentMag** [comment]
the issue is still here indeed, need to reload at every change to have the test consider the change

**Comment by sheremet-va** [comment]
I cannot reproduce any "still happens for me". Tried on Mac and Windows.

**Comment by jimmyn** [comment]
@sheremet-va apparently it only happens in Cursor and not in latest VS Code.

I have Cursor Version: 0.41.3, VSCode Version: 1.91.1

**Comment by sheremet-va** [comment]
> @sheremet-va apparently it only happens in Cursor and not in latest VS Code.
> 
> I have Cursor Version: 0.41.3, VSCode Version: 1.91.1

What OS are you using?

**Comment by sheremet-va** [comment]
Can you provide any output? You can open this tab by typing "> Show Vitest Output Channel" in a search bar

**Comment by jimmyn** [comment]
Here you have the output, I also attached the video.

![2024-10-02 17 21 44](https://github.com/user-attachments/assets/648ea658-1f48-4a32-ae82-2fb88944651d)


<details><summary>Vitest Output</summary>
<p>

[INFO 17:21:02] [v1.2.12] Vitest extension is activated because Vitest is installed or there is a Vite/Vitest config file in the workspace.
[INFO 17:21:02] [API] Running Vitest v2.1.1 (vitest-demo/vitest.config.ts) with Node.js@v20.15.1: /Users/dmitriy/.nvm/current/bin/node 
[INFO 17:21:02] [API] Vitest v2.1.1 (vitest-demo/vitest.config.ts) process 12709 created
[INFO 17:21:08] [API] Collecting tests: demo.test.ts
[17:21:08] Not starting the runner because tests are being collected
[17:21:08] There is no test run for "demo.test.ts"
[17:21:08] No test run to finish for /Users/dmitriy/Work/vitest-demo/demo.test.ts
[INFO 17:21:11] Running 1 file(s) with name pattern: ^\s?demo$
[17:21:11] The runner is starting because tests /Users/dmitriy/Work/vitest-demo/demo.test.ts were started due to a file change
[17:21:11] Enqueuing "demo"
[17:21:11] No task result for "demo", assuming the test just started running
[17:21:11] Marking "demo" as passed
[17:21:11] Ending test run demo.test.ts
[INFO 17:21:22] [API] Vitest process 12709 closed successfully
[INFO 17:21:22] [API] Running Vitest v2.1.1 (vitest-demo/vitest.config.ts) with Node.js@v20.15.1: /Users/dmitriy/.nvm/current/bin/node 
[INFO 17:21:23] [API] Vitest v2.1.1 (vitest-demo/vitest.config.ts) process 12766 created
[INFO 17:21:23] [API] Collecting tests: demo.test.ts
[17:21:23] Not starting the runner because tests are being collected
[17:21:23] There is no test run for "demo.test.ts"
[17:21:23] No test run to finish for /Users/dmitriy/Work/vitest-demo/demo.test.ts
[INFO 17:21:46] Running 1 file(s) with name pattern: ^\s?demo$
[17:21:46] The runner is starting because tests /Users/dmitriy/Work/vitest-demo/demo.test.ts were started due to a file change
[17:21:46] Enqueuing "demo"
[17:21:46] No task result for "demo", assuming the test just started running
[17:21:46] Marking "demo" as passed
[17:21:46] Ending test run demo.test.ts
[INFO 17:21:56] Running 1 file(s) with name pattern: ^\s?demo$
[17:21:56] The runner is starting because tests /Users/dmitriy/Work/vitest-demo/demo.test.ts were started due to a file change
[17:21:56] Enqueuing "demo"
[17:21:56] No task result for "demo", assuming the test just started running
[17:21:56] Marking "demo" as passed
[17:21:56] Ending test run demo.test.ts
[INFO 17:21:57] Running 1 file(s) with name pattern: ^\s?demo$
[17:21:57] The runner is starting because tests /Users/dmitriy/Work/vitest-demo/demo.test.ts were started due to a file change
[17:21:57] Enqueuing "demo"
[17:21:57] No task result for "demo", assuming the test just started running
[17:21:57] Marking "demo" as passed
[17:21:57] Ending test run demo.test.ts
[INFO 17:22:02] [API] Vitest process 12766 closed successfully
[INFO 17:22:02] [API] Running Vitest v2.1.1 (vitest-demo/vitest.config.ts) with Node.js@v20.15.1: /Users/dmitriy/.nvm/current/bin/node 
[INFO 17:22:02] [API] Vitest v2.1.1 (vitest-demo/vitest.config.ts) process 12811 created
[INFO 17:22:02] [API] Collecting tests: demo.test.ts
[17:22:02] Not starting the runner because tests are being collected
[17:22:02] There is no test run for "demo.test.ts"
[17:22:02] No test run to finish for /Users/dmitriy/Work/vitest-demo/demo.test.ts
[INFO 17:22:04] Running 1 file(s) with name pattern: ^\s?demo$
[17:22:04] The runner is starting because tests /Users/dmitriy/Work/vitest-demo/demo.test.ts were started due to a file change
[17:22:04] Enqueuing "demo"
[17:22:04] No task result for "demo", assuming the test just started running
[17:22:04] No errors found for "demo.test.ts"
[17:22:04] Marking "demo" as failed with 1 errors
[17:22:04] No errors found for "demo.test.ts"
[17:22:04] Ending test run demo.test.ts


</p>
</details>

**Comment by sheremet-va** [comment]
Still cannot reproduce, but made a possible fix. Can you check with 1.2.16?

**Comment by jimmyn** [comment]
Its weird that I dont see debug logs even if I set log level to debug in vitest extention config

<details><summary>Vitest Output</summary>
<p>

[INFO 17:49:27] [v1.2.15] Vitest extension is activated because Vitest is installed or there is a Vite/Vitest config file in the workspace.
[INFO 17:49:27] [API] Running Vitest v2.1.1 (vitest-demo/vitest.config.ts) with Node.js@v20.15.1: /Users/dmitriy/.nvm/current/bin/node 
[INFO 17:49:28] [API] Vitest v2.1.1 (vitest-demo/vitest.config.ts) process 16485 created
[INFO 17:49:28] [API] Collecting tests: demo.test.ts
[17:49:28] Not starting the runner because tests are being collected
[17:49:28] There is no test run for "demo.test.ts"
[17:49:28] No test run to finish for /Users/dmitriy/Work/vitest-demo/demo.test.ts
[INFO 17:49:29] Running 1 file(s) with name pattern: ^\s?demo$
[17:49:29] The runner is starting because tests /Users/dmitriy/Work/vitest-demo/demo.test.ts were started due to a file change
[17:49:29] Enqueuing "demo"
[17:49:29] No task result for "demo", assuming the test just started running
[17:49:29] Marking "demo" as passed
[17:49:29] Ending test run demo.test.ts
[INFO 17:49:33] Running 1 file(s) with name pattern: ^\s?demo$
[17:49:33] The runner is starting because tests /Users/dmitriy/Work/vitest-demo/demo.test.ts were started due to a file change
[17:49:33] Enqueuing "demo"
[17:49:33] No task result for "demo", assuming the test just started running
[17:49:33] Marking "demo" as passed
[17:49:33] Ending test run demo.test.ts
[INFO 17:49:34] Running 1 file(s) with name pattern: ^\s?demo$
[17:49:34] The runner is starting because tests /Users/dmitriy/Work/vitest-demo/demo.test.ts were started due to a file change
[17:49:34] Enqueuing "demo"
[17:49:34] No task result for "demo", assuming the test just started running
[17:49:34] Marking "demo" as passed
[17:49:34] Ending test run demo.test.ts
[INFO 17:49:39] [API] Vitest process 16485 closed successfully
[INFO 17:49:39] [API] Running Vitest v2.1.1 (vitest-demo/vitest.config.ts) with Node.js@v20.15.1: /Users/dmitriy/.nvm/current/bin/node 
[INFO 17:49:39] [API] Vitest v2.1.1 (vitest-demo/vitest.config.ts) process 16542 created
[INFO 17:49:39] [API] Collecting tests: demo.test.ts
[17:49:39] Not starting the runner because tests are being collected
[17:49:39] There is no test run for "demo.test.ts"
[17:49:39] No test run to finish for /Users/dmitriy/Work/vitest-demo/demo.test.ts
[INFO 17:49:40] Running 1 file(s) with name pattern: ^\s?demo$
[17:49:40] The runner is starting because tests /Users/dmitriy/Work/vitest-demo/demo.test.ts were started due to a file change
[17:49:40] Enqueuing "demo"
[17:49:40] No task result for "demo", assuming the test just started running
[17:49:40] No errors found for "demo.test.ts"
[17:49:40] Marking "demo" as failed with 1 errors
[17:49:40] No errors found for "demo.test.ts"
[17:49:40] Ending test run demo.test.ts


</p>
</details>

**Comment by sheremet-va** [comment]
There are two possible reasons for that:

1. Cursor watcher didn't trigger the event
2. `fs.stat` failed with an error

In 1.2.16 `fs.stat` was replaced with vscode's `stat`, and I now log the error if there are any. So if it still doesn't log `[VSCODE]`, then it's an issue with Cursor.

**Comment by jimmyn** [comment]
Doesn't seem to be working for me

<details><summary>Details</summary>
<p>

[INFO 17:53:10] [v1.2.16] Vitest extension is activated because Vitest is installed or there is a Vite/Vitest config file in the workspace.
[INFO 17:53:11] [API] Running Vitest v2.1.1 (vitest-demo/vitest.config.ts) with Node.js@v20.15.1: /Users/dmitriy/.nvm/current/bin/node 
[INFO 17:53:11] [API] Vitest v2.1.1 (vitest-demo/vitest.config.ts) process 16860 created
[INFO 17:53:11] [API] Collecting tests: demo.test.ts
[17:53:11] Not starting the runner because tests are being collected
[17:53:11] There is no test run for "demo.test.ts"
[17:53:11] No test run to finish for demo.test.ts
[INFO 17:53:13] Running 1 file(s) with name pattern: ^\s?demo$
[17:53:13] The runner is starting because tests demo.test.ts were started due to a file change
[17:53:13] Enqueuing "demo"
[17:53:13] No task result for "demo", assuming the test just started running
[17:53:13] No errors found for "demo.test.ts"
[17:53:13] Marking "demo" as failed with 1 errors
[17:53:13] No errors found for "demo.test.ts"
[17:53:13] Ending test run demo.test.ts
[INFO 17:53:15] Running 1 file(s) with name pattern: ^\s?demo$
[17:53:15] The runner is starting because tests demo.test.ts were started due to a file change
[17:53:15] Enqueuing "demo"
[17:53:16] No task result for "demo", assuming the test just started running
[17:53:16] No errors found for "demo.test.ts"
[17:53:16] Marking "demo" as failed with 1 errors
[17:53:16] No errors found for "demo.test.ts"
[17:53:16] Ending test run demo.test.ts
[INFO 17:53:19] Running 1 file(s) with name pattern: ^\s?demo$
[17:53:19] The runner is starting because tests demo.test.ts were started due to a file change
[17:53:19] Enqueuing "demo"
[17:53:19] No task result for "demo", assuming the test just started running
[17:53:19] No errors found for "demo.test.ts"
[17:53:19] Marking "demo" as failed with 1 errors
[17:53:19] No errors found for "demo.test.ts"
[17:53:19] Ending test run demo.test.ts
[INFO 17:53:22] [API] Vitest process 16860 closed successfully
[INFO 17:53:22] [API] Running Vitest v2.1.1 (vitest-demo/vitest.config.ts) with Node.js@v20.15.1: /Users/dmitriy/.nvm/current/bin/node 
[INFO 17:53:22] [API] Vitest v2.1.1 (vitest-demo/vitest.config.ts) process 16930 created
[INFO 17:53:22] [API] Collecting tests: demo.test.ts
[17:53:22] Not starting the runner because tests are being collected
[17:53:22] There is no test run for "demo.test.ts"
[17:53:22] No test run to finish for demo.test.ts
[INFO 17:53:23] Running 1 file(s) with name pattern: ^\s?demo$
[17:53:23] The runner is starting because tests demo.test.ts were started due to a file change
[17:53:23] Enqueuing "demo"
[17:53:23] No task result for "demo", assuming the test just started running
[17:53:23] No errors found for "demo.test.ts"
[17:53:23] Marking "demo" as failed with 1 errors
[17:53:23] No errors found for "demo.test.ts"
[17:53:23] Ending test run demo.test.ts
[INFO 17:53:26] [API] Vitest process 16930 closed successfully
[INFO 17:53:26] [API] Running Vitest v2.1.1 (vitest-demo/vitest.config.ts) with Node.js@v20.15.1: /Users/dmitriy/.nvm/current/bin/node 
[INFO 17:53:26] [API] Vitest v2.1.1 (vitest-demo/vitest.config.ts) process 16956 created
[INFO 17:53:27] [API] Collecting tests: demo.test.ts
[17:53:27] Not starting the runner because tests are being collected
[17:53:27] There is no test run for "demo.test.ts"
[17:53:27] No test run to finish for demo.test.ts
[INFO 17:53:28] Running 1 file(s) with name pattern: ^\s?demo$
[17:53:28] The runner is starting because tests demo.test.ts were started due to a file change
[17:53:28] Enqueuing "demo"
[17:53:28] No task result for "demo", assuming the test just started running
[17:53:28] No errors found for "demo.test.ts"
[17:53:28] Marking "demo" as failed with 1 errors
[17:53:28] No errors found for "demo.test.ts"
[17:53:28] Ending test run demo.test.ts


</p>
</details>

**Comment by sheremet-va** [comment]
Oops, I messed up the condition in the latest version. Releasing a fix in a minute.

**Comment by jimmyn** [comment]
I can confirm that version 1.2.0 works fine, but versions 1.2.1 and later do not.

**Comment by sheremet-va** [comment]
> I can confirm that version 1.2.0 works fine, but versions 1.2.1 and later do not.

1.2.0 changed the watcher from `chokidar` to the vscode one. It's obviously the culprit. Check 1.2.17 when it's released.

**Comment by jimmyn** [comment]
@sheremet-va 1.2.17 doesn't work for me

**Comment by sheremet-va** [comment]
> @sheremet-va 1.2.17 doesn't work for me

Any output?

**Comment by jimmyn** [comment]
Looks the same

<details><summary>Details</summary>
<p>

[INFO 18:10:42] [v1.2.17] Vitest extension is activated because Vitest is installed or there is a Vite/Vitest config file in the workspace.
[INFO 18:10:42] [API] Running Vitest v2.1.1 (vitest-demo/vitest.config.ts) with Node.js@v20.15.1: /Users/dmitriy/.nvm/current/bin/node 
[INFO 18:10:42] [API] Vitest v2.1.1 (vitest-demo/vitest.config.ts) process 19446 created
[INFO 18:10:43] [API] Collecting tests: demo.test.ts
[18:10:43] Not starting the runner because tests are being collected
[18:10:43] There is no test run for "demo.test.ts"
[18:10:43] No test run to finish for demo.test.ts
[INFO 18:10:46] Running 1 file(s) with name pattern: ^\s?demo$
[18:10:46] The runner is starting because tests demo.test.ts were started due to a file change
[18:10:46] Enqueuing "demo"
[18:10:46] No task result for "demo", assuming the test just started running
[18:10:46] Marking "demo" as passed
[18:10:46] Ending test run demo.test.ts
[INFO 18:10:50] Running 1 file(s) with name pattern: ^\s?demo$
[18:10:50] The runner is starting because tests demo.test.ts were started due to a file change
[18:10:50] Enqueuing "demo"
[18:10:50] No task result for "demo", assuming the test just started running
[18:10:50] Marking "demo" as passed
[18:10:50] Ending test run demo.test.ts
[INFO 18:10:50] Running 1 file(s) with name pattern: ^\s?demo$
[18:10:50] The runner is starting because tests demo.test.ts were started due to a file change
[18:10:50] Enqueuing "demo"
[18:10:50] No task result for "demo", assuming the test just started running
[18:10:50] Marking "demo" as passed
[18:10:50] Ending test run demo.test.ts
[INFO 18:10:53] Running 1 file(s) with name pattern: ^\s?demo$
[18:10:53] The runner is starting because tests demo.test.ts were started due to a file change
[18:10:53] Enqueuing "demo"
[18:10:54] No task result for "demo", assuming the test just started running
[18:10:54] Marking "demo" as passed
[18:10:54] Ending test run demo.test.ts
[INFO 18:10:56] [API] Vitest process 19446 closed successfully
[INFO 18:10:56] [API] Running Vitest v2.1.1 (vitest-demo/vitest.config.ts) with Node.js@v20.15.1: /Users/dmitriy/.nvm/current/bin/node 
[INFO 18:10:56] [API] Vitest v2.1.1 (vitest-demo/vitest.config.ts) process 19508 created
[INFO 18:10:56] [API] Collecting tests: demo.test.ts
[18:10:56] Not starting the runner because tests are being collected
[18:10:56] There is no test run for "demo.test.ts"
[18:10:56] No test run to finish for demo.test.ts
[INFO 18:10:57] Running 1 file(s) with name pattern: ^\s?demo$
[18:10:57] The runner is starting because tests demo.test.ts were started due to a file change
[18:10:57] Enqueuing "demo"
[18:10:57] No task result for "demo", assuming the test just started running
[18:10:57] No errors found for "demo.test.ts"
[18:10:57] Marking "demo" as failed with 1 errors
[18:10:57] No errors found for "demo.test.ts"
[18:10:57] Ending test run demo.test.ts


</p>
</details>

**Comment by sheremet-va** [comment]
Seems like it is an issue with your Cursor configuration then. Check that test files are not excluded in the watcher. You can search for "watch" in the settings.

**Comment by jimmyn** [comment]
It does seem to work if I include .ts files manually

<img width="472" alt="image" src="https://github.com/user-attachments/assets/cf68af79-3bf3-4f99-8b63-9096df596c6c">

**Comment by sheremet-va** [comment]
> It does seem to work if I include .ts files manually
> 
> <img alt="image" width="472" src="https://private-user-images.githubusercontent.com/5391775/372948069-cf68af79-3bf3-4f99-8b63-9096df596c6c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4ODY5NzEsIm5iZiI6MTcyNzg4NjY3MSwicGF0aCI6Ii81MzkxNzc1LzM3Mjk0ODA2OS1jZjY4YWY3OS0zYmYzLTRmOTktOGI2My05MDk2ZGY1OTZjNmMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMDJUMTYzMTExWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTUwY2UxMDYyMWJjMDg4M2ExNWQwODMxMzQ1ZTAzMmY0ZDIwNDc3ZDljY2UyOWFlODhmNjUyZWE3MTI4ZmZhMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.tjGnKapOgGxUifF--cQNdgDthSkTSsWqrEcFydW3F24">

This will only match files in the root folder, as far as I understand. Vitest default is `**/*` which matches every file that vscode can watch in the workspace folder 🤔

**Comment by jimmyn** [comment]
Yes `**/*` also works, seems the default value is not set somehow

**Comment by jimmyn** [comment]
Awesome, it works now, thanks a lot!
